### ISSUE TITLE
Internet symbol in the KDE Plasma menu

### ISSUE THREAD

**Issue by ghost** [L4ki/Breeze-openSUSE-Icons#1]
The internet symbol in the KDE Plasma menu is white-black. The same happens with the "Breeze-KDE-Story-Icons ".

Original:
![img1](https://user-images.githubusercontent.com/94405857/147980874-507ff1e8-bd91-4f2d-b031-1b0836c4e4aa.png)

Breeze-openSUSE-Icons / Breeze-KDE-Story-Icons
![img2](https://user-images.githubusercontent.com/94405857/147980922-bb692b09-a475-44e9-bb48-ea42f982dcd4.png)

Can you check that?

**Comment by L4ki** [comment]
Hi Suryavarman-II, 

I would ask your to download icons here: 

"Breeze-openSUSE Dark Icons" : https://www.pling.com/p/1339434/

"Breeze KDE-Story-Dark Icons": https://www.pling.com/p/1334700/

I'll correct later and here at Github.

Thank you and a big greeting.

**Comment by ghost** [comment]
Ok thank you.
The files on "pling" do work properly.
